version: '3.1'

services:

  db:
    container_name: comics-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: omka2061
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: comics-app
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - pgadmin


  pgadmin:
    container_name: comics-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mcscare12@gmail.com
      PGADMIN_DEFAULT_PASSWORD: omka2061
    ports:
      - "5050:80"

  