"""Create database

Revision ID: 1fd4e725d5a6
Revises: 
Create Date: 2023-12-10 00:04:40.877475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd4e725d5a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comic_author'), 'comic', ['author'], unique=False)
    op.create_index(op.f('ix_comic_id'), 'comic', ['id'], unique=False)
    op.create_index(op.f('ix_comic_rating'), 'comic', ['rating'], unique=False)
    op.create_index(op.f('ix_comic_title'), 'comic', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('VALUE', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_VALUE'), 'rating', ['VALUE'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_VALUE'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_comic_title'), table_name='comic')
    op.drop_index(op.f('ix_comic_rating'), table_name='comic')
    op.drop_index(op.f('ix_comic_id'), table_name='comic')
    op.drop_index(op.f('ix_comic_author'), table_name='comic')
    op.drop_table('comic')
    # ### end Alembic commands ###
